### ISSUE TITLE
add_executable called with incorrect number of arguments

### ISSUE THREAD

**Issue by thelou1s** [WuFengXue/WuFengXue.github.io#1]
（您好，因为网站没有留言系统，故提交到这里了，如有不便会删除）

看了您的文章“微信语音编解码实现（三）—— lame 移植”，按文章操作完运行后编译不通过，查了stackvoverflow等无果：

Build error logs:
Caused by: com.android.builder.errors.EvalIssueException: 
E:\Android\demo_android\lame\src\main\cpp\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at E:\Android\demo_android\lame\src\main\cpp\CMakeLists.txt:27 (add_executable):  add_executable called with incorrect number of arguments
(Android Studio 4.2, AndroidNdk 11)

另外，文中“源文件的选取见 lame 源码/frontend/Makefile.in 文件 mp3rtp_SOURCES 和 mp3x_SOURCES 字段的值”不太理解，要进一步删除Makefile.in中的什么代码吗？

文章很不错，谢谢分享

**Comment by WuFengXue** [comment]
您好。

第1个问题：可以考虑把 ndk 版本降级试试，或者查下 CMakeList.txt 的规则看看，不同版本接口可能会调整。

第2个问题：【“源文件的选取见 lame 源码/frontend/Makefile.in 文件 mp3rtp_SOURCES 和 mp3x_SOURCES 字段的值”】这里描述的应该是要删除的文件的选取，对应的是 mp3x 模块，因为其依赖了 ‘gtk/gtk.h’ 会导致报错
（可以用比较工具，例如 BeyondCompare，比较 lame 源码与 WeChatVoiceCodec 工程的源码进行对照）


<img width="1115" alt="image" src="https://user-images.githubusercontent.com/12031430/139364519-c6544f72-46d1-47db-83fc-6541eb6decc6.png">


<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12031430/139364234-a546b322-b3dd-4864-9aaf-8d6c5baee63f.png">

**Comment by thelou1s** [comment]
好了，谢谢，您的github代码可以运行：）

但in.mp3转出来的in.pcm好像有点问题（或者说如何确定转后的pcm每个字节无误？）？和我用python代码或格式工厂转后的完全不一样。您知道这有可能是什么原因吗？


```
import os
from pydub import AudioSegment

def trans_mp3_to_wav(file_uri):
    print('trans_mp3_to_wav, file_uri = ' + file_uri)
    audio = AudioSegment.from_mp3(file_uri)
    audio.export(file_uri + ".wav", format="wav")
    # os.remove(file_uri)
    

if __name__ == '__main__':
    path = r"./data/tmp"
    listdir_files = os.listdir(path)
    mp3_files = [path + "/" + f for f in listdir_files if f.endswith('.mp3')]

    for mp3_file in mp3_files:
        trans_mp3_to_wav(mp3_file)
```

![image](https://user-images.githubusercontent.com/5654770/139833736-b587232e-900b-43aa-84f4-2baa6a3b95b5.png)

**Comment by WuFengXue** [comment]
不同编解码器采用的算法是不一样的，你如果要做对比，使用 python 版的 lame 解码器生成的文件做对比会合理一些。

关于确保解出来的字节数全部正确的问题，这块你可以细看下 lame 的源码，我个人理解是如果整个处理过程出现任何一个错误，代码中都会做相应的处理，比如报错或抛异常之类的。如果没有出现这种场景，那就可以默认其是正确的。

如果有异常情况，那应该要归于 lame 库的 bug，可以细看源码修复或者提 issue 给原作者。
